### ISSUE TITLE
⚡️ 데이트 피커가 오른쪽으로 쏠리는 문제

### ISSUE THREAD

**Issue by seochan99** [moduManito/manito-iOS#5]
## What's Problem

오른쪽으로 쏠리고, 외국 날짜 기준으로 되어 있고, 1분단위 여서 
- Locale = Korean으로 설정하였고,
- Interval은 10min으로 설정하고 테스트 해본 결과 

<img width="639" alt="Screenshot 2023-07-22 at 7 12 50 PM" src="https://github.com/moduManito/manito-iOS/assets/78739194/7c3204bd-8f6c-40e3-9960-e41d5380564f">

다른 문제는 해결 했으나, 이와 같이 여전히 쏠림 문제가 있습니다. 

해결책 아시면.. 해결법 알려주세요 ㅎ_ㅎ...

**Comment by Rayleigh190** [comment]
![스크린샷 2023-07-22 23 34 58](https://github.com/moduManito/manito-iOS/assets/86937253/f11a4745-9196-4f87-8356-a3df44b882b6)

스토리보드에서는 어려울것 같고 DatePicker를 IBOutlet 연결해서 아래 코드로 조정하면 됩니다!

`publicDatePicker.contentHorizontalAlignment = .center`

**Comment by seochan99** [comment]
천재만재다................😳
고맙습니다:))
하나배워가여!
